### ISSUE TITLE
log_subcmds is breaking shebangs 

### ISSUE THREAD

**Issue by yamrzou** [sudo-project/sudo#194]
Causing "bad interpreter: No such file or directory"

Steps:

As the `root` user:
- In `visudo` add the following lines (taken from [here](https://www.sudo.ws/posts/2022/05/sudo-for-blue-teams-how-to-control-and-log-better/)):
```
Defaults log_format=json
Defaults log_subcmds
Defaults:%wheel runchroot=*
Defaults log_input, log_output
Defaults !log_passwords
Defaults log_servers=0.0.0.0
```
- create a file `debug` in `root`'s home, with the following content:
```
#!/bin/bash
echo hello
```
- Make executable: `chmod +x debug`
- Add user `bob` to sudoers: `usermod -aG sudo bob`

============================================

Try with `log_subcmds` enabled:
- login as user `bob`
- `sudo bash`
- `cd $HOME`
- `./debug`
bash: ./debug: /bin/bash: bad interpreter: No such file or directory

Try with `log_subcmds` disabled (commented):
- login as user `bob`
- `sudo bash`
- `cd $HOME`
- `./debug`
hello

**Comment by millert** [comment]
What version of sudo are you running and on what OS?

**Comment by yamrzou** [comment]
OS: Debian GNU/Linux 11 (bullseye)
Sudo version 1.9.12

**Comment by millert** [comment]
Thanks, I've managed to reproduce it.  The key is that the debug script must not be in the same directory that sudo was started from.  It looks like there is still an issue with running relative commands from a different cwd.

**Comment by millert** [comment]
Closing this as fixed by [8db1eb0](https://github.com/sudo-project/sudo/commit/8db1eb0c8bfa025468029294fb9aa805e8c860a6)

**Comment by yamrzou** [comment]
I think there is still an issue with `log_subcmds`:

I'm following the following tutorial: https://soapbox.pub/install/. 

When trying to install Erlang by executing the following inside the sudo session (`sudo -Hu pleroma bash`):
```
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.0
echo ". $HOME/.asdf/asdf.sh" >> ~/.bashrc
echo ". $HOME/.asdf/completions/asdf.bash" >> ~/.bashrc
exec bash
asdf plugin-add erlang
asdf plugin-add elixir
asdf install
```

When `log_subcmds` is enabled, the last step fails with:
```
Configure failed.
/var/lib/pleroma/.asdf/plugins/erlang/kerl: 926: ./otp_build: not found
```

When I comment it out, the installation succeeds:
```
Erlang/OTP 24.3.4.2 (asdf_24.3.4.2) has been successfully built
```

I couldn't make a smaller example, but the only changing factor was whether `log_subcmds` was enabled.

**Comment by millert** [comment]
Thanks for reporting this, I was able to reproduce it with the information you provided.  This is a different issue that only shows up when running a command with a very large argument vector.  It is fixed by [fe001b6](https://github.com/sudo-project/sudo/commit/fe001b6ffedb783f92fce34042de8a482897b342) which will be in the next sudo 1.9.13 beta.

**Comment by yamrzou** [comment]
Thank you for the quick fix!
